# Generated by Django 4.0.2 on 2022-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=45, verbose_name='Apellido'),
        ),
    ]
