# Generated by Django 4.0.2 on 2022-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_city_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
