# Generated by Django 4.0.2 on 2022-05-08 02:48

import Django_Blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_image', validators=[Django_Blog.utils.validate_image], verbose_name='Imagen de perfil'),
        ),
    ]
