# Generated by Django 4.0.2 on 2022-05-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Biografia'),
        ),
    ]
