# Generated by Django 4.0.2 on 2022-05-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desactivo', 'Desactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
