# Generated by Django 4.0.2 on 2022-05-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_city_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='Ciudad',
        ),
    ]
