# Generated by Django 4.0.2 on 2022-02-04 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre categoria')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Url')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': ['id_category'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False, verbose_name='Id articulo')),
                ('name', models.CharField(max_length=55, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='article/images', verbose_name='Imagen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('resume', models.CharField(max_length=150, verbose_name='Descripcion del articulo')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Url')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'Articulo',
                'ordering': ['id_article'],
            },
        ),
    ]
