# Generated by Django 4.0.2 on 2022-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
