# Generated by Django 4.0.2 on 2022-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
