# Generated by Django 4.0.2 on 2022-05-08 02:44

import Django_Blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_category_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/images', validators=[Django_Blog.utils.validate_image], verbose_name='Imagen'),
        ),
    ]
